name: selenoid-stack

services:
  selenoid1:
    image: aerokube/selenoid:latest-release
    container_name: selenoid1
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/browsers.json:/etc/selenoid/browsers.json:ro"
    command:
      - "-conf"
      - "/etc/selenoid/browsers.json"
      - "-limit"
      - "4"
      - "-container-network"
      - "grid"
    environment:
      - TZ=Asia/Yerevan
    networks:
      - grid
    restart: unless-stopped

  selenoid2:
      image: aerokube/selenoid:latest-release
      container_name: selenoid2
      ports:
        - "4446:4444"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./selenoid/browsers.json:/etc/selenoid/browsers.json:ro"
      command:
        - "-conf"
        - "/etc/selenoid/browsers.json"
        - "-limit"
        - "4"
        - "-container-network"
        - "grid"
      environment:
        - TZ=Asia/Yerevan
      networks:
        - grid
      restart: unless-stopped

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    ports:
      - "9090:8080"
    command:
      - "--selenoid-uri"
      - "http://selenoid1:4444"
    depends_on:
      - selenoid1
    networks:
      - grid
    restart: unless-stopped

  ggr:
    image: aerokube/ggr:latest-release
    container_name: ggr
    ports:
      - "4445:4444"
    volumes:
      - ./ggr:/etc/grid-router
    command:
      - "-listen"
      - ":4444"
      - "-quotaDir"
      - "/etc/grid-router/quota"
      - "-guests-allowed"
      - "-verbose"
    networks:
        - grid
    restart: unless-stopped

  ggr-ui:
    image: aerokube/ggr-ui:latest-release
    container_name: ggr-ui
    ports:
      - "8888:8888"
    volumes:
      - ./ggr:/etc/grid-router
    depends_on:
      - ggr
    networks:
      - grid
    restart: unless-stopped

networks:
  grid:
    name: grid