---
- name: Pull docker images
  command: docker-compose pull
  args:
    chdir: "{{ playbook_dir }}/../../"

- name: Start containers
  command: docker-compose up -d
  args:
    chdir: "{{ playbook_dir }}/../../"