---
- name: Deploy Selenoid infrastructure
  hosts: local
  become: false

  roles:
    - playbook-selenoid/roles/docker
    - playbook-selenoid/roles/rendering_configs
    - playbook-selenoid/roles/docker-compose
